# Permalink
permalink: /posts/:title/

# Setup
title: Mark Tareshawty
url: "http://marktareshawty.com"
basename: ""

description: >
  This is the corner of the Internet that contains Mark Tareshawty's musings
  and semi-tolerable jokes.

author:
  name: Mark Tareshawty
  email: mark@marktareshawty.com

# Build settings
markdown: kramdown
sass:
  sass_dir: _scss
  style: compressed

# Custom Vars
github:
  repo: https://github.com/tarebyte/tarebyte.github.io

# Custom Vars
handle: tarebyte
flickr_url: https://www.flickr.com/photos/marktareshawty/

gems:
  - jemoji
  - jekyll-mentions

